version: '3.8'

services:
  backend:
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://your-frontend-domain.com
    restart: always

  frontend:
    environment:
      - REACT_APP_API_URL=https://your-backend-domain.com
      - REACT_APP_API_BASE_URL=https://your-backend-domain.com/api
    restart: always

  mongodb:
    restart: always